author: 'Martin Thurn <mthurn@cpan.org>'
build_requires:
  Encode: 0
  I18N::Charset: 0
  Test::More: 0
  WWW::Search::Test: 2.265
distribution_type: module
generated_by: Module::Install version 0.61
license: perl
name: WWW-Search-Yahoo
no_index:
  directory:
    - inc
    - t
requires:
  Data::Dumper: 0
  Date::Manip: 0
  HTML::TreeBuilder: 0
  URI: 0
  URI::Escape: 0
  WWW::Search: 2.523
  perl: 5.004
version: 2.405
